# version param is deprecated
name: malanka-coffee

services:
  postgres:
    image: postgres:15-alpine
    container_name: malanka-postgresql
    restart: unless-stopped
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: malanka
      POSTGRES_PASSWORD: malanka
      POSTGRES_DB: malanka_coffee
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres-data: { }
