name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths: [ src/** ]
    types: [ opened, synchronize ]

jobs:
  build-and-test:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4
      - name: Set up JDK 21
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 #v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 #v4

      - name: Build and Test with Gradle Wrapper
        run: ./gradlew check bootJar

      - name: Test Coverage
        id: jacoco
        uses: madrapps/jacoco-report@e4bbaf00a0b8920cb86a448ae3ec0fc6f6bfeacc #v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Coverage Report
          update-comment: true
          continue-on-error: false
          skip-if-no-changes: true
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: .
          name: 'malanka-coffee'
          if-no-files-found: 'error'
          retention-days: 7
  docker-build-check:
    needs: [build-and-test]
    uses: ./.github/workflows/docker-build-check.yaml