name: Check Dockerfile Build

on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]

jobs:
  dockerfile-check:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: 'malanka-coffee'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Dockerfile
        uses: docker/build-push-action@v6
