name: Dependency Review

on:
  pull_request:

permissions:
  contents: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4

      - name: Perform dependency review
        uses: actions/dependency-review-action@v4