---
name: Main Workflow

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths: [ src/** ]
    types: [ opened, synchronize ]

jobs:
  CI:
    uses: ./.github/workflows/ci.yaml
    permissions:
      pull-requests: write